/// Taxonomy of Latin American countries, states/provinces, and cities.
/// Used to populate Explorer filter dropdowns with full geographic data.
class LatamTaxonomy {
  LatamTaxonomy._();

  /// All Latin American countries sorted alphabetically.
  static const List<String> countries = [
    'Argentina',
    'Bolivia',
    'Brasil',
    'Chile',
    'Colombia',
    'Costa Rica',
    'Cuba',
    'Ecuador',
    'El Salvador',
    'Guatemala',
    'Haití',
    'Honduras',
    'México',
    'Nicaragua',
    'Panamá',
    'Paraguay',
    'Perú',
    'Puerto Rico',
    'República Dominicana',
    'Uruguay',
    'Venezuela',
  ];

  /// Map: country → list of states/provinces/departments.
  static const Map<String, List<String>> states = {
    'Argentina': [
      'Buenos Aires',
      'CABA',
      'Catamarca',
      'Chaco',
      'Chubut',
      'Córdoba',
      'Corrientes',
      'Entre Ríos',
      'Formosa',
      'Jujuy',
      'La Pampa',
      'La Rioja',
      'Mendoza',
      'Misiones',
      'Neuquén',
      'Río Negro',
      'Salta',
      'San Juan',
      'San Luis',
      'Santa Cruz',
      'Santa Fe',
      'Santiago del Estero',
      'Tierra del Fuego',
      'Tucumán',
    ],
    'Bolivia': [
      'Beni',
      'Chuquisaca',
      'Cochabamba',
      'La Paz',
      'Oruro',
      'Pando',
      'Potosí',
      'Santa Cruz',
      'Tarija',
    ],
    'Brasil': [
      'Acre',
      'Alagoas',
      'Amapá',
      'Amazonas',
      'Bahia',
      'Ceará',
      'Distrito Federal',
      'Espírito Santo',
      'Goiás',
      'Maranhão',
      'Mato Grosso',
      'Mato Grosso do Sul',
      'Minas Gerais',
      'Pará',
      'Paraíba',
      'Paraná',
      'Pernambuco',
      'Piauí',
      'Rio de Janeiro',
      'Rio Grande do Norte',
      'Rio Grande do Sul',
      'Rondônia',
      'Roraima',
      'Santa Catarina',
      'São Paulo',
      'Sergipe',
      'Tocantins',
    ],
    'Chile': [
      'Arica y Parinacota',
      'Tarapacá',
      'Antofagasta',
      'Atacama',
      'Coquimbo',
      'Valparaíso',
      'Metropolitana',
      "O'Higgins",
      'Maule',
      'Ñuble',
      'Biobío',
      'Araucanía',
      'Los Ríos',
      'Los Lagos',
      'Aysén',
      'Magallanes',
    ],
    'Colombia': [
      'Amazonas',
      'Antioquia',
      'Arauca',
      'Atlántico',
      'Bogotá D.C.',
      'Bolívar',
      'Boyacá',
      'Caldas',
      'Caquetá',
      'Casanare',
      'Cauca',
      'Cesar',
      'Chocó',
      'Córdoba',
      'Cundinamarca',
      'Guainía',
      'Guaviare',
      'Huila',
      'La Guajira',
      'Magdalena',
      'Meta',
      'Nariño',
      'Norte de Santander',
      'Putumayo',
      'Quindío',
      'Risaralda',
      'San Andrés',
      'Santander',
      'Sucre',
      'Tolima',
      'Valle del Cauca',
      'Vaupés',
      'Vichada',
    ],
    'Costa Rica': [
      'Alajuela',
      'Cartago',
      'Guanacaste',
      'Heredia',
      'Limón',
      'Puntarenas',
      'San José',
    ],
    'Cuba': [
      'Artemisa',
      'Camagüey',
      'Ciego de Ávila',
      'Cienfuegos',
      'Granma',
      'Guantánamo',
      'Holguín',
      'Isla de la Juventud',
      'La Habana',
      'Las Tunas',
      'Matanzas',
      'Mayabeque',
      'Pinar del Río',
      'Sancti Spíritus',
      'Santiago de Cuba',
      'Villa Clara',
    ],
    'Ecuador': [
      'Azuay',
      'Bolívar',
      'Cañar',
      'Carchi',
      'Chimborazo',
      'Cotopaxi',
      'El Oro',
      'Esmeraldas',
      'Galápagos',
      'Guayas',
      'Imbabura',
      'Loja',
      'Los Ríos',
      'Manabí',
      'Morona Santiago',
      'Napo',
      'Orellana',
      'Pastaza',
      'Pichincha',
      'Santa Elena',
      'Santo Domingo',
      'Sucumbíos',
      'Tungurahua',
      'Zamora Chinchipe',
    ],
    'El Salvador': [
      'Ahuachapán',
      'Cabañas',
      'Chalatenango',
      'Cuscatlán',
      'La Libertad',
      'La Paz',
      'La Unión',
      'Morazán',
      'San Miguel',
      'San Salvador',
      'San Vicente',
      'Santa Ana',
      'Sonsonate',
      'Usulután',
    ],
    'Guatemala': [
      'Alta Verapaz',
      'Baja Verapaz',
      'Chimaltenango',
      'Chiquimula',
      'El Progreso',
      'Escuintla',
      'Guatemala',
      'Huehuetenango',
      'Izabal',
      'Jalapa',
      'Jutiapa',
      'Petén',
      'Quetzaltenango',
      'Quiché',
      'Retalhuleu',
      'Sacatepéquez',
      'San Marcos',
      'Santa Rosa',
      'Sololá',
      'Suchitepéquez',
      'Totonicapán',
      'Zacapa',
    ],
    'Haití': [
      'Artibonite',
      'Centre',
      'Grand\'Anse',
      'Nippes',
      'Nord',
      'Nord-Est',
      'Nord-Ouest',
      'Ouest',
      'Sud',
      'Sud-Est',
    ],
    'Honduras': [
      'Atlántida',
      'Choluteca',
      'Colón',
      'Comayagua',
      'Copán',
      'Cortés',
      'El Paraíso',
      'Francisco Morazán',
      'Gracias a Dios',
      'Intibucá',
      'Islas de la Bahía',
      'La Paz',
      'Lempira',
      'Ocotepeque',
      'Olancho',
      'Santa Bárbara',
      'Valle',
      'Yoro',
    ],
    'México': [
      'Aguascalientes',
      'Baja California',
      'Baja California Sur',
      'Campeche',
      'Chiapas',
      'Chihuahua',
      'Ciudad de México',
      'Coahuila',
      'Colima',
      'Durango',
      'Estado de México',
      'Guanajuato',
      'Guerrero',
      'Hidalgo',
      'Jalisco',
      'Michoacán',
      'Morelos',
      'Nayarit',
      'Nuevo León',
      'Oaxaca',
      'Puebla',
      'Querétaro',
      'Quintana Roo',
      'San Luis Potosí',
      'Sinaloa',
      'Sonora',
      'Tabasco',
      'Tamaulipas',
      'Tlaxcala',
      'Veracruz',
      'Yucatán',
      'Zacatecas',
    ],
    'Nicaragua': [
      'Boaco',
      'Carazo',
      'Chinandega',
      'Chontales',
      'Estelí',
      'Granada',
      'Jinotega',
      'León',
      'Madriz',
      'Managua',
      'Masaya',
      'Matagalpa',
      'Nueva Segovia',
      'RACCN',
      'RACCS',
      'Río San Juan',
      'Rivas',
    ],
    'Panamá': [
      'Bocas del Toro',
      'Chiriquí',
      'Coclé',
      'Colón',
      'Darién',
      'Herrera',
      'Los Santos',
      'Panamá',
      'Panamá Oeste',
      'Veraguas',
    ],
    'Paraguay': [
      'Alto Paraguay',
      'Alto Paraná',
      'Amambay',
      'Asunción',
      'Boquerón',
      'Caaguazú',
      'Caazapá',
      'Canindeyú',
      'Central',
      'Concepción',
      'Cordillera',
      'Guairá',
      'Itapúa',
      'Misiones',
      'Ñeembucú',
      'Paraguarí',
      'Presidente Hayes',
      'San Pedro',
    ],
    'Perú': [
      'Amazonas',
      'Áncash',
      'Apurímac',
      'Arequipa',
      'Ayacucho',
      'Cajamarca',
      'Callao',
      'Cusco',
      'Huancavelica',
      'Huánuco',
      'Ica',
      'Junín',
      'La Libertad',
      'Lambayeque',
      'Lima',
      'Loreto',
      'Madre de Dios',
      'Moquegua',
      'Pasco',
      'Piura',
      'Puno',
      'San Martín',
      'Tacna',
      'Tumbes',
      'Ucayali',
    ],
    'Puerto Rico': [
      'Adjuntas',
      'Aguadilla',
      'Arecibo',
      'Bayamón',
      'Caguas',
      'Carolina',
      'Guayama',
      'Humacao',
      'Mayagüez',
      'Ponce',
      'San Juan',
    ],
    'República Dominicana': [
      'Azua',
      'Bahoruco',
      'Barahona',
      'Dajabón',
      'Distrito Nacional',
      'Duarte',
      'El Seibo',
      'Elías Piña',
      'Espaillat',
      'Hato Mayor',
      'Hermanas Mirabal',
      'Independencia',
      'La Altagracia',
      'La Romana',
      'La Vega',
      'María Trinidad Sánchez',
      'Monseñor Nouel',
      'Monte Cristi',
      'Monte Plata',
      'Pedernales',
      'Peravia',
      'Puerto Plata',
      'Samaná',
      'San Cristóbal',
      'San José de Ocoa',
      'San Juan',
      'San Pedro de Macorís',
      'Sánchez Ramírez',
      'Santiago',
      'Santiago Rodríguez',
      'Santo Domingo',
      'Valverde',
    ],
    'Uruguay': [
      'Artigas',
      'Canelones',
      'Cerro Largo',
      'Colonia',
      'Durazno',
      'Flores',
      'Florida',
      'Lavalleja',
      'Maldonado',
      'Montevideo',
      'Paysandú',
      'Río Negro',
      'Rivera',
      'Rocha',
      'Salto',
      'San José',
      'Soriano',
      'Tacuarembó',
      'Treinta y Tres',
    ],
    'Venezuela': [
      'Amazonas',
      'Anzoátegui',
      'Apure',
      'Aragua',
      'Barinas',
      'Bolívar',
      'Carabobo',
      'Cojedes',
      'Delta Amacuro',
      'Distrito Capital',
      'Falcón',
      'Guárico',
      'Lara',
      'Mérida',
      'Miranda',
      'Monagas',
      'Nueva Esparta',
      'Portuguesa',
      'Sucre',
      'Táchira',
      'Trujillo',
      'Vargas',
      'Yaracuy',
      'Zulia',
    ],
  };

  /// Map: "Country|State" → list of cities.
  static const Map<String, List<String>> cities = {
    // ── Argentina ──
    'Argentina|Buenos Aires': [
      'La Plata',
      'Mar del Plata',
      'Bahía Blanca',
      'Tandil',
      'Quilmes',
      'Lanús',
      'Lomas de Zamora',
      'Avellaneda',
      'Morón',
      'San Isidro',
      'Tigre',
      'Vicente López',
      'Pilar',
      'Zárate',
      'Campana',
      'Junín',
      'Olavarría',
      'Necochea',
      'Pergamino',
      'San Nicolás',
    ],
    'Argentina|CABA': [
      'Buenos Aires',
    ],
    'Argentina|Catamarca': [
      'San Fernando del Valle de Catamarca',
    ],
    'Argentina|Chaco': [
      'Resistencia',
      'Presidencia Roque Sáenz Peña',
    ],
    'Argentina|Chubut': [
      'Rawson',
      'Comodoro Rivadavia',
      'Trelew',
      'Puerto Madryn',
    ],
    'Argentina|Córdoba': [
      'Córdoba',
      'Villa María',
      'Río Cuarto',
      'San Francisco',
      'Villa Carlos Paz',
      'Alta Gracia',
    ],
    'Argentina|Corrientes': [
      'Corrientes',
      'Goya',
    ],
    'Argentina|Entre Ríos': [
      'Paraná',
      'Concordia',
      'Gualeguaychú',
    ],
    'Argentina|Formosa': [
      'Formosa',
    ],
    'Argentina|Jujuy': [
      'San Salvador de Jujuy',
    ],
    'Argentina|La Pampa': [
      'Santa Rosa',
    ],
    'Argentina|La Rioja': [
      'La Rioja',
    ],
    'Argentina|Mendoza': [
      'Mendoza',
      'San Rafael',
      'Godoy Cruz',
      'Guaymallén',
      'Las Heras',
    ],
    'Argentina|Misiones': [
      'Posadas',
      'Oberá',
      'Eldorado',
    ],
    'Argentina|Neuquén': [
      'Neuquén',
      'San Martín de los Andes',
    ],
    'Argentina|Río Negro': [
      'Viedma',
      'San Carlos de Bariloche',
      'General Roca',
      'Cipolletti',
    ],
    'Argentina|Salta': [
      'Salta',
      'San Ramón de la Nueva Orán',
      'Tartagal',
    ],
    'Argentina|San Juan': [
      'San Juan',
    ],
    'Argentina|San Luis': [
      'San Luis',
      'Villa Mercedes',
    ],
    'Argentina|Santa Cruz': [
      'Río Gallegos',
      'Caleta Olivia',
    ],
    'Argentina|Santa Fe': [
      'Santa Fe',
      'Rosario',
      'Rafaela',
      'Venado Tuerto',
      'Reconquista',
    ],
    'Argentina|Santiago del Estero': [
      'Santiago del Estero',
    ],
    'Argentina|Tierra del Fuego': [
      'Ushuaia',
      'Río Grande',
    ],
    'Argentina|Tucumán': [
      'San Miguel de Tucumán',
      'Yerba Buena',
      'Tafí Viejo',
    ],

    // ── Bolivia ──
    'Bolivia|Beni': ['Trinidad', 'Riberalta'],
    'Bolivia|Chuquisaca': ['Sucre'],
    'Bolivia|Cochabamba': ['Cochabamba', 'Quillacollo', 'Sacaba', 'Tiquipaya'],
    'Bolivia|La Paz': ['La Paz', 'El Alto', 'Viacha'],
    'Bolivia|Oruro': ['Oruro'],
    'Bolivia|Pando': ['Cobija'],
    'Bolivia|Potosí': ['Potosí'],
    'Bolivia|Santa Cruz': [
      'Santa Cruz de la Sierra',
      'Montero',
      'Warnes',
      'La Guardia',
    ],
    'Bolivia|Tarija': ['Tarija', 'Yacuiba'],

    // ── Brasil ──
    'Brasil|Acre': ['Rio Branco', 'Cruzeiro do Sul'],
    'Brasil|Alagoas': ['Maceió', 'Arapiraca'],
    'Brasil|Amapá': ['Macapá', 'Santana'],
    'Brasil|Amazonas': ['Manaus', 'Parintins'],
    'Brasil|Bahia': [
      'Salvador',
      'Feira de Santana',
      'Vitória da Conquista',
      'Camaçari',
      'Itabuna',
      'Lauro de Freitas',
      'Ilhéus',
    ],
    'Brasil|Ceará': [
      'Fortaleza',
      'Caucaia',
      'Juazeiro do Norte',
      'Maracanaú',
      'Sobral',
    ],
    'Brasil|Distrito Federal': ['Brasília'],
    'Brasil|Espírito Santo': [
      'Vitória',
      'Vila Velha',
      'Serra',
      'Cariacica',
    ],
    'Brasil|Goiás': [
      'Goiânia',
      'Aparecida de Goiânia',
      'Anápolis',
      'Rio Verde',
    ],
    'Brasil|Maranhão': [
      'São Luís',
      'Imperatriz',
      'Timon',
      'Caxias',
    ],
    'Brasil|Mato Grosso': [
      'Cuiabá',
      'Várzea Grande',
      'Rondonópolis',
      'Sinop',
    ],
    'Brasil|Mato Grosso do Sul': [
      'Campo Grande',
      'Dourados',
      'Três Lagoas',
      'Corumbá',
    ],
    'Brasil|Minas Gerais': [
      'Belo Horizonte',
      'Uberlândia',
      'Contagem',
      'Juiz de Fora',
      'Betim',
      'Montes Claros',
      'Uberaba',
      'Ribeirão das Neves',
      'Governador Valadares',
      'Ipatinga',
    ],
    'Brasil|Pará': [
      'Belém',
      'Ananindeua',
      'Santarém',
      'Marabá',
    ],
    'Brasil|Paraíba': [
      'João Pessoa',
      'Campina Grande',
      'Santa Rita',
    ],
    'Brasil|Paraná': [
      'Curitiba',
      'Londrina',
      'Maringá',
      'Ponta Grossa',
      'Cascavel',
      'Foz do Iguaçu',
      'São José dos Pinhais',
      'Colombo',
    ],
    'Brasil|Pernambuco': [
      'Recife',
      'Jaboatão dos Guararapes',
      'Olinda',
      'Caruaru',
      'Petrolina',
      'Paulista',
    ],
    'Brasil|Piauí': ['Teresina', 'Parnaíba'],
    'Brasil|Rio de Janeiro': [
      'Rio de Janeiro',
      'São Gonçalo',
      'Duque de Caxias',
      'Nova Iguaçu',
      'Niterói',
      'Belford Roxo',
      'Campos dos Goytacazes',
      'São João de Meriti',
      'Petrópolis',
      'Volta Redonda',
    ],
    'Brasil|Rio Grande do Norte': [
      'Natal',
      'Mossoró',
      'Parnamirim',
    ],
    'Brasil|Rio Grande do Sul': [
      'Porto Alegre',
      'Caxias do Sul',
      'Pelotas',
      'Canoas',
      'Santa Maria',
      'Gravataí',
      'Viamão',
      'Novo Hamburgo',
      'São Leopoldo',
      'Passo Fundo',
    ],
    'Brasil|Rondônia': ['Porto Velho', 'Ji-Paraná'],
    'Brasil|Roraima': ['Boa Vista'],
    'Brasil|Santa Catarina': [
      'Florianópolis',
      'Joinville',
      'Blumenau',
      'São José',
      'Chapecó',
      'Criciúma',
      'Itajaí',
      'Balneário Camboriú',
    ],
    'Brasil|São Paulo': [
      'São Paulo',
      'Guarulhos',
      'Campinas',
      'São Bernardo do Campo',
      'Santo André',
      'Osasco',
      'São José dos Campos',
      'Ribeirão Preto',
      'Sorocaba',
      'Santos',
      'Mauá',
      'São José do Rio Preto',
      'Mogi das Cruzes',
      'Diadema',
      'Piracicaba',
      'Bauru',
      'Jundiaí',
      'Carapicuíba',
      'Limeira',
      'Taubaté',
    ],
    'Brasil|Sergipe': ['Aracaju', 'Nossa Senhora do Socorro'],
    'Brasil|Tocantins': ['Palmas', 'Araguaína'],

    // ── Chile ──
    'Chile|Arica y Parinacota': ['Arica'],
    'Chile|Tarapacá': ['Iquique', 'Alto Hospicio'],
    'Chile|Antofagasta': ['Antofagasta', 'Calama'],
    'Chile|Atacama': ['Copiapó', 'Vallenar'],
    'Chile|Coquimbo': ['La Serena', 'Coquimbo', 'Ovalle'],
    'Chile|Valparaíso': [
      'Valparaíso',
      'Viña del Mar',
      'Quilpué',
      'Villa Alemana',
      'San Antonio',
    ],
    'Chile|Metropolitana': [
      'Santiago',
      'Puente Alto',
      'Maipú',
      'La Florida',
      'Las Condes',
      'Peñalolén',
      'Providencia',
      'Ñuñoa',
      'San Bernardo',
      'Renca',
    ],
    "Chile|O'Higgins": ['Rancagua', 'San Fernando'],
    'Chile|Maule': ['Talca', 'Curicó', 'Linares', 'Constitución'],
    'Chile|Ñuble': ['Chillán'],
    'Chile|Biobío': [
      'Concepción',
      'Talcahuano',
      'Los Ángeles',
      'Chiguayante',
      'Coronel',
    ],
    'Chile|Araucanía': ['Temuco', 'Padre las Casas', 'Villarrica'],
    'Chile|Los Ríos': ['Valdivia'],
    'Chile|Los Lagos': ['Puerto Montt', 'Osorno', 'Castro'],
    'Chile|Aysén': ['Coyhaique'],
    'Chile|Magallanes': ['Punta Arenas'],

    // ── Colombia ──
    'Colombia|Amazonas': ['Leticia'],
    'Colombia|Antioquia': [
      'Medellín',
      'Bello',
      'Itagüí',
      'Envigado',
      'Apartadó',
      'Rionegro',
      'Turbo',
    ],
    'Colombia|Arauca': ['Arauca'],
    'Colombia|Atlántico': [
      'Barranquilla',
      'Soledad',
      'Malambo',
    ],
    'Colombia|Bogotá D.C.': ['Bogotá'],
    'Colombia|Bolívar': ['Cartagena', 'Magangué'],
    'Colombia|Boyacá': ['Tunja', 'Duitama', 'Sogamoso'],
    'Colombia|Caldas': ['Manizales', 'La Dorada'],
    'Colombia|Caquetá': ['Florencia'],
    'Colombia|Casanare': ['Yopal'],
    'Colombia|Cauca': ['Popayán', 'Santander de Quilichao'],
    'Colombia|Cesar': ['Valledupar', 'Aguachica'],
    'Colombia|Chocó': ['Quibdó'],
    'Colombia|Córdoba': ['Montería', 'Cereté', 'Lorica'],
    'Colombia|Cundinamarca': [
      'Soacha',
      'Facatativá',
      'Zipaquirá',
      'Chía',
      'Fusagasugá',
      'Girardot',
      'Mosquera',
    ],
    'Colombia|Guainía': ['Inírida'],
    'Colombia|Guaviare': ['San José del Guaviare'],
    'Colombia|Huila': ['Neiva', 'Pitalito'],
    'Colombia|La Guajira': ['Riohacha', 'Maicao'],
    'Colombia|Magdalena': ['Santa Marta', 'Ciénaga'],
    'Colombia|Meta': ['Villavicencio', 'Acacías'],
    'Colombia|Nariño': ['Pasto', 'Ipiales', 'Tumaco'],
    'Colombia|Norte de Santander': ['Cúcuta', 'Ocaña'],
    'Colombia|Putumayo': ['Mocoa'],
    'Colombia|Quindío': ['Armenia', 'Calarcá'],
    'Colombia|Risaralda': ['Pereira', 'Dosquebradas'],
    'Colombia|San Andrés': ['San Andrés'],
    'Colombia|Santander': [
      'Bucaramanga',
      'Floridablanca',
      'Girón',
      'Piedecuesta',
      'Barrancabermeja',
    ],
    'Colombia|Sucre': ['Sincelejo'],
    'Colombia|Tolima': ['Ibagué', 'Espinal'],
    'Colombia|Valle del Cauca': [
      'Cali',
      'Buenaventura',
      'Palmira',
      'Tuluá',
      'Cartago',
      'Buga',
      'Jamundí',
    ],
    'Colombia|Vaupés': ['Mitú'],
    'Colombia|Vichada': ['Puerto Carreño'],

    // ── Costa Rica ──
    'Costa Rica|Alajuela': ['Alajuela', 'San Carlos', 'Grecia'],
    'Costa Rica|Cartago': ['Cartago', 'Paraíso', 'Turrialba'],
    'Costa Rica|Guanacaste': ['Liberia', 'Nicoya', 'Santa Cruz'],
    'Costa Rica|Heredia': ['Heredia', 'San Pablo', 'Barva'],
    'Costa Rica|Limón': ['Limón', 'Guápiles', 'Siquirres'],
    'Costa Rica|Puntarenas': ['Puntarenas', 'Esparza', 'Quepos'],
    'Costa Rica|San José': [
      'San José',
      'Escazú',
      'Desamparados',
      'Curridabat',
      'Moravia',
      'Tibás',
    ],

    // ── Cuba ──
    'Cuba|Artemisa': ['Artemisa'],
    'Cuba|Camagüey': ['Camagüey'],
    'Cuba|Ciego de Ávila': ['Ciego de Ávila'],
    'Cuba|Cienfuegos': ['Cienfuegos'],
    'Cuba|Granma': ['Bayamo', 'Manzanillo'],
    'Cuba|Guantánamo': ['Guantánamo', 'Baracoa'],
    'Cuba|Holguín': ['Holguín'],
    'Cuba|Isla de la Juventud': ['Nueva Gerona'],
    'Cuba|La Habana': ['La Habana', 'Habana Vieja', 'Vedado', 'Miramar'],
    'Cuba|Las Tunas': ['Las Tunas'],
    'Cuba|Matanzas': ['Matanzas', 'Varadero'],
    'Cuba|Mayabeque': ['San José de las Lajas'],
    'Cuba|Pinar del Río': ['Pinar del Río', 'Viñales'],
    'Cuba|Sancti Spíritus': ['Sancti Spíritus', 'Trinidad'],
    'Cuba|Santiago de Cuba': ['Santiago de Cuba'],
    'Cuba|Villa Clara': ['Santa Clara'],

    // ── Ecuador ──
    'Ecuador|Azuay': ['Cuenca', 'Gualaceo'],
    'Ecuador|Bolívar': ['Guaranda'],
    'Ecuador|Cañar': ['Azogues'],
    'Ecuador|Carchi': ['Tulcán'],
    'Ecuador|Chimborazo': ['Riobamba'],
    'Ecuador|Cotopaxi': ['Latacunga'],
    'Ecuador|El Oro': ['Machala', 'Pasaje'],
    'Ecuador|Esmeraldas': ['Esmeraldas', 'Atacames'],
    'Ecuador|Galápagos': ['Puerto Ayora'],
    'Ecuador|Guayas': [
      'Guayaquil',
      'Durán',
      'Milagro',
      'Daule',
      'Samborondón',
    ],
    'Ecuador|Imbabura': ['Ibarra', 'Otavalo'],
    'Ecuador|Loja': ['Loja'],
    'Ecuador|Los Ríos': ['Babahoyo', 'Quevedo'],
    'Ecuador|Manabí': ['Portoviejo', 'Manta', 'Chone'],
    'Ecuador|Morona Santiago': ['Macas'],
    'Ecuador|Napo': ['Tena'],
    'Ecuador|Orellana': ['Francisco de Orellana'],
    'Ecuador|Pastaza': ['Puyo'],
    'Ecuador|Pichincha': ['Quito', 'Sangolquí', 'Cayambe'],
    'Ecuador|Santa Elena': ['Santa Elena', 'Salinas', 'La Libertad'],
    'Ecuador|Santo Domingo': ['Santo Domingo'],
    'Ecuador|Sucumbíos': ['Lago Agrio'],
    'Ecuador|Tungurahua': ['Ambato', 'Baños'],
    'Ecuador|Zamora Chinchipe': ['Zamora'],

    // ── El Salvador ──
    'El Salvador|Ahuachapán': ['Ahuachapán'],
    'El Salvador|Cabañas': ['Sensuntepeque'],
    'El Salvador|Chalatenango': ['Chalatenango'],
    'El Salvador|Cuscatlán': ['Cojutepeque'],
    'El Salvador|La Libertad': [
      'Santa Tecla',
      'Antiguo Cuscatlán',
      'Ciudad Arce',
    ],
    'El Salvador|La Paz': ['Zacatecoluca'],
    'El Salvador|La Unión': ['La Unión'],
    'El Salvador|Morazán': ['San Francisco Gotera'],
    'El Salvador|San Miguel': ['San Miguel'],
    'El Salvador|San Salvador': [
      'San Salvador',
      'Soyapango',
      'Mejicanos',
      'Apopa',
      'Ciudad Delgado',
      'Ilopango',
    ],
    'El Salvador|San Vicente': ['San Vicente'],
    'El Salvador|Santa Ana': ['Santa Ana', 'Metapán', 'Chalchuapa'],
    'El Salvador|Sonsonate': ['Sonsonate'],
    'El Salvador|Usulután': ['Usulután'],

    // ── Guatemala ──
    'Guatemala|Alta Verapaz': ['Cobán', 'San Pedro Carchá'],
    'Guatemala|Baja Verapaz': ['Salamá'],
    'Guatemala|Chimaltenango': ['Chimaltenango'],
    'Guatemala|Chiquimula': ['Chiquimula', 'Esquipulas'],
    'Guatemala|El Progreso': ['Guastatoya'],
    'Guatemala|Escuintla': ['Escuintla'],
    'Guatemala|Guatemala': [
      'Ciudad de Guatemala',
      'Mixco',
      'Villa Nueva',
      'San Miguel Petapa',
      'Amatitlán',
    ],
    'Guatemala|Huehuetenango': ['Huehuetenango'],
    'Guatemala|Izabal': ['Puerto Barrios'],
    'Guatemala|Jalapa': ['Jalapa'],
    'Guatemala|Jutiapa': ['Jutiapa'],
    'Guatemala|Petén': ['Flores', 'Santa Elena'],
    'Guatemala|Quetzaltenango': ['Quetzaltenango'],
    'Guatemala|Quiché': ['Santa Cruz del Quiché'],
    'Guatemala|Retalhuleu': ['Retalhuleu'],
    'Guatemala|Sacatepéquez': ['Antigua Guatemala'],
    'Guatemala|San Marcos': ['San Marcos'],
    'Guatemala|Santa Rosa': ['Cuilapa'],
    'Guatemala|Sololá': ['Sololá', 'Panajachel'],
    'Guatemala|Suchitepéquez': ['Mazatenango'],
    'Guatemala|Totonicapán': ['Totonicapán'],
    'Guatemala|Zacapa': ['Zacapa'],

    // ── Haití ──
    'Haití|Artibonite': ['Gonaïves', 'Saint-Marc'],
    'Haití|Centre': ['Hinche'],
    "Haití|Grand'Anse": ['Jérémie'],
    'Haití|Nippes': ['Miragoâne'],
    'Haití|Nord': ['Cap-Haïtien'],
    'Haití|Nord-Est': ['Fort-Liberté'],
    'Haití|Nord-Ouest': ['Port-de-Paix'],
    'Haití|Ouest': ['Port-au-Prince', 'Pétion-Ville', 'Delmas', 'Carrefour'],
    'Haití|Sud': ['Les Cayes'],
    'Haití|Sud-Est': ['Jacmel'],

    // ── Honduras ──
    'Honduras|Atlántida': ['La Ceiba', 'Tela'],
    'Honduras|Choluteca': ['Choluteca'],
    'Honduras|Colón': ['Tocoa', 'Trujillo'],
    'Honduras|Comayagua': ['Comayagua', 'Siguatepeque'],
    'Honduras|Copán': ['Santa Rosa de Copán'],
    'Honduras|Cortés': [
      'San Pedro Sula',
      'Choloma',
      'La Lima',
      'Villanueva',
      'Puerto Cortés',
    ],
    'Honduras|El Paraíso': ['Danlí', 'El Paraíso'],
    'Honduras|Francisco Morazán': [
      'Tegucigalpa',
      'Comayagüela',
      'Valle de Ángeles',
    ],
    'Honduras|Gracias a Dios': ['Puerto Lempira'],
    'Honduras|Intibucá': ['La Esperanza'],
    'Honduras|Islas de la Bahía': ['Roatán', 'La Ceiba'],
    'Honduras|La Paz': ['La Paz'],
    'Honduras|Lempira': ['Gracias'],
    'Honduras|Ocotepeque': ['Nueva Ocotepeque'],
    'Honduras|Olancho': ['Juticalpa', 'Catacamas'],
    'Honduras|Santa Bárbara': ['Santa Bárbara'],
    'Honduras|Valle': ['Nacaome', 'San Lorenzo'],
    'Honduras|Yoro': ['El Progreso', 'Yoro', 'Olanchito'],

    // ── México ──
    'México|Aguascalientes': ['Aguascalientes'],
    'México|Baja California': [
      'Tijuana',
      'Mexicali',
      'Ensenada',
      'Tecate',
      'Rosarito',
    ],
    'México|Baja California Sur': [
      'La Paz',
      'Los Cabos',
      'San José del Cabo',
    ],
    'México|Campeche': ['Campeche', 'Ciudad del Carmen'],
    'México|Chiapas': [
      'Tuxtla Gutiérrez',
      'San Cristóbal de las Casas',
      'Tapachula',
      'Comitán',
    ],
    'México|Chihuahua': [
      'Chihuahua',
      'Ciudad Juárez',
      'Delicias',
      'Cuauhtémoc',
    ],
    'México|Ciudad de México': [
      'Ciudad de México',
      'Coyoacán',
      'Tlalpan',
      'Xochimilco',
      'Iztapalapa',
      'Gustavo A. Madero',
      'Álvaro Obregón',
    ],
    'México|Coahuila': [
      'Saltillo',
      'Torreón',
      'Monclova',
      'Piedras Negras',
    ],
    'México|Colima': ['Colima', 'Manzanillo', 'Tecomán'],
    'México|Durango': ['Durango', 'Gómez Palacio', 'Lerdo'],
    'México|Estado de México': [
      'Toluca',
      'Ecatepec',
      'Naucalpan',
      'Tlalnepantla',
      'Nezahualcóyotl',
      'Atizapán',
      'Huixquilucan',
      'Metepec',
      'Coacalco',
      'Cuautitlán Izcalli',
    ],
    'México|Guanajuato': [
      'León',
      'Irapuato',
      'Celaya',
      'Salamanca',
      'Guanajuato',
      'San Miguel de Allende',
    ],
    'México|Guerrero': [
      'Acapulco',
      'Chilpancingo',
      'Iguala',
      'Zihuatanejo',
      'Taxco',
    ],
    'México|Hidalgo': ['Pachuca', 'Tulancingo', 'Tula de Allende'],
    'México|Jalisco': [
      'Guadalajara',
      'Zapopan',
      'Tlaquepaque',
      'Tonalá',
      'Puerto Vallarta',
      'Lagos de Moreno',
      'Tlajomulco',
    ],
    'México|Michoacán': [
      'Morelia',
      'Uruapan',
      'Zamora',
      'Lázaro Cárdenas',
    ],
    'México|Morelos': ['Cuernavaca', 'Cuautla', 'Jiutepec', 'Temixco'],
    'México|Nayarit': ['Tepic', 'Bahía de Banderas'],
    'México|Nuevo León': [
      'Monterrey',
      'San Pedro Garza García',
      'Guadalupe',
      'Apodaca',
      'San Nicolás de los Garza',
      'Santa Catarina',
      'General Escobedo',
    ],
    'México|Oaxaca': [
      'Oaxaca de Juárez',
      'Salina Cruz',
      'Juchitán',
      'Huatulco',
    ],
    'México|Puebla': [
      'Puebla',
      'Tehuacán',
      'San Martín Texmelucan',
      'Atlixco',
      'Cholula',
    ],
    'México|Querétaro': [
      'Querétaro',
      'San Juan del Río',
      'El Marqués',
      'Corregidora',
    ],
    'México|Quintana Roo': [
      'Cancún',
      'Chetumal',
      'Playa del Carmen',
      'Cozumel',
      'Tulum',
    ],
    'México|San Luis Potosí': [
      'San Luis Potosí',
      'Ciudad Valles',
      'Soledad de Graciano Sánchez',
    ],
    'México|Sinaloa': [
      'Culiacán',
      'Mazatlán',
      'Los Mochis',
      'Guasave',
    ],
    'México|Sonora': [
      'Hermosillo',
      'Ciudad Obregón',
      'Nogales',
      'Guaymas',
      'Navojoa',
    ],
    'México|Tabasco': [
      'Villahermosa',
      'Cárdenas',
      'Comalcalco',
    ],
    'México|Tamaulipas': [
      'Reynosa',
      'Matamoros',
      'Tampico',
      'Nuevo Laredo',
      'Ciudad Victoria',
      'Ciudad Madero',
    ],
    'México|Tlaxcala': ['Tlaxcala', 'Apizaco'],
    'México|Veracruz': [
      'Veracruz',
      'Xalapa',
      'Coatzacoalcos',
      'Córdoba',
      'Poza Rica',
      'Orizaba',
      'Minatitlán',
      'Boca del Río',
    ],
    'México|Yucatán': [
      'Mérida',
      'Valladolid',
      'Progreso',
      'Kanasín',
      'Umán',
    ],
    'México|Zacatecas': ['Zacatecas', 'Fresnillo', 'Guadalupe'],

    // ── Nicaragua ──
    'Nicaragua|Boaco': ['Boaco'],
    'Nicaragua|Carazo': ['Jinotepe', 'Diriamba'],
    'Nicaragua|Chinandega': ['Chinandega', 'El Viejo', 'Corinto'],
    'Nicaragua|Chontales': ['Juigalpa'],
    'Nicaragua|Estelí': ['Estelí'],
    'Nicaragua|Granada': ['Granada'],
    'Nicaragua|Jinotega': ['Jinotega'],
    'Nicaragua|León': ['León', 'La Paz Centro'],
    'Nicaragua|Madriz': ['Somoto'],
    'Nicaragua|Managua': [
      'Managua',
      'Tipitapa',
      'Ciudad Sandino',
    ],
    'Nicaragua|Masaya': ['Masaya'],
    'Nicaragua|Matagalpa': ['Matagalpa'],
    'Nicaragua|Nueva Segovia': ['Ocotal'],
    'Nicaragua|RACCN': ['Bilwi'],
    'Nicaragua|RACCS': ['Bluefields'],
    'Nicaragua|Río San Juan': ['San Carlos'],
    'Nicaragua|Rivas': ['Rivas', 'San Juan del Sur'],

    // ── Panamá ──
    'Panamá|Bocas del Toro': ['Bocas del Toro', 'Changuinola'],
    'Panamá|Chiriquí': ['David', 'Boquete', 'Puerto Armuelles'],
    'Panamá|Coclé': ['Penonomé', 'Aguadulce'],
    'Panamá|Colón': ['Colón'],
    'Panamá|Darién': ['La Palma'],
    'Panamá|Herrera': ['Chitré'],
    'Panamá|Los Santos': ['Las Tablas', 'Pedasí'],
    'Panamá|Panamá': [
      'Ciudad de Panamá',
      'San Miguelito',
      'Tocumen',
      'Las Cumbres',
      'Pacora',
    ],
    'Panamá|Panamá Oeste': ['La Chorrera', 'Arraiján'],
    'Panamá|Veraguas': ['Santiago'],

    // ── Paraguay ──
    'Paraguay|Alto Paraguay': ['Fuerte Olimpo'],
    'Paraguay|Alto Paraná': [
      'Ciudad del Este',
      'Presidente Franco',
      'Hernandarias'
    ],
    'Paraguay|Amambay': ['Pedro Juan Caballero'],
    'Paraguay|Asunción': ['Asunción'],
    'Paraguay|Boquerón': ['Filadelfia'],
    'Paraguay|Caaguazú': ['Coronel Oviedo', 'Caaguazú'],
    'Paraguay|Caazapá': ['Caazapá'],
    'Paraguay|Canindeyú': ['Salto del Guairá'],
    'Paraguay|Central': [
      'San Lorenzo',
      'Luque',
      'Fernando de la Mora',
      'Lambaré',
      'Capiatá',
      'Limpio',
      'Ñemby',
      'Mariano Roque Alonso',
    ],
    'Paraguay|Concepción': ['Concepción'],
    'Paraguay|Cordillera': ['Caacupé'],
    'Paraguay|Guairá': ['Villarrica'],
    'Paraguay|Itapúa': ['Encarnación', 'Hohenau'],
    'Paraguay|Misiones': ['San Juan Bautista'],
    'Paraguay|Ñeembucú': ['Pilar'],
    'Paraguay|Paraguarí': ['Paraguarí'],
    'Paraguay|Presidente Hayes': ['Villa Hayes'],
    'Paraguay|San Pedro': ['San Pedro'],

    // ── Perú ──
    'Perú|Amazonas': ['Chachapoyas', 'Bagua'],
    'Perú|Áncash': ['Huaraz', 'Chimbote'],
    'Perú|Apurímac': ['Abancay', 'Andahuaylas'],
    'Perú|Arequipa': ['Arequipa', 'Mollendo', 'Camaná'],
    'Perú|Ayacucho': ['Ayacucho'],
    'Perú|Cajamarca': ['Cajamarca', 'Jaén'],
    'Perú|Callao': ['Callao'],
    'Perú|Cusco': ['Cusco', 'Sicuani', 'Quillabamba'],
    'Perú|Huancavelica': ['Huancavelica'],
    'Perú|Huánuco': ['Huánuco', 'Tingo María'],
    'Perú|Ica': ['Ica', 'Chincha Alta', 'Pisco', 'Nazca'],
    'Perú|Junín': ['Huancayo', 'Tarma', 'La Merced'],
    'Perú|La Libertad': ['Trujillo', 'Chepén', 'Pacasmayo'],
    'Perú|Lambayeque': ['Chiclayo', 'Lambayeque', 'Ferreñafe'],
    'Perú|Lima': [
      'Lima',
      'San Isidro',
      'Miraflores',
      'Surco',
      'San Borja',
      'La Molina',
      'Los Olivos',
      'San Juan de Lurigancho',
      'Ate',
      'Chorrillos',
      'San Martín de Porres',
      'Comas',
      'Villa El Salvador',
      'Huacho',
    ],
    'Perú|Loreto': ['Iquitos', 'Yurimaguas'],
    'Perú|Madre de Dios': ['Puerto Maldonado'],
    'Perú|Moquegua': ['Moquegua', 'Ilo'],
    'Perú|Pasco': ['Cerro de Pasco'],
    'Perú|Piura': ['Piura', 'Sullana', 'Talara', 'Paita'],
    'Perú|Puno': ['Puno', 'Juliaca'],
    'Perú|San Martín': ['Tarapoto', 'Moyobamba'],
    'Perú|Tacna': ['Tacna'],
    'Perú|Tumbes': ['Tumbes'],
    'Perú|Ucayali': ['Pucallpa'],

    // ── Puerto Rico ──
    'Puerto Rico|Adjuntas': ['Adjuntas'],
    'Puerto Rico|Aguadilla': ['Aguadilla'],
    'Puerto Rico|Arecibo': ['Arecibo'],
    'Puerto Rico|Bayamón': ['Bayamón'],
    'Puerto Rico|Caguas': ['Caguas'],
    'Puerto Rico|Carolina': ['Carolina'],
    'Puerto Rico|Guayama': ['Guayama'],
    'Puerto Rico|Humacao': ['Humacao'],
    'Puerto Rico|Mayagüez': ['Mayagüez'],
    'Puerto Rico|Ponce': ['Ponce'],
    'Puerto Rico|San Juan': ['San Juan'],

    // ── República Dominicana ──
    'República Dominicana|Azua': ['Azua'],
    'República Dominicana|Bahoruco': ['Neyba'],
    'República Dominicana|Barahona': ['Barahona'],
    'República Dominicana|Dajabón': ['Dajabón'],
    'República Dominicana|Distrito Nacional': ['Santo Domingo'],
    'República Dominicana|Duarte': ['San Francisco de Macorís'],
    'República Dominicana|El Seibo': ['El Seibo'],
    'República Dominicana|Elías Piña': ['Comendador'],
    'República Dominicana|Espaillat': ['Moca'],
    'República Dominicana|Hato Mayor': ['Hato Mayor'],
    'República Dominicana|Hermanas Mirabal': ['Salcedo'],
    'República Dominicana|Independencia': ['Jimaní'],
    'República Dominicana|La Altagracia': ['Higüey', 'Punta Cana'],
    'República Dominicana|La Romana': ['La Romana'],
    'República Dominicana|La Vega': ['La Vega', 'Constanza', 'Jarabacoa'],
    'República Dominicana|María Trinidad Sánchez': ['Nagua'],
    'República Dominicana|Monseñor Nouel': ['Bonao'],
    'República Dominicana|Monte Cristi': ['Monte Cristi'],
    'República Dominicana|Monte Plata': ['Monte Plata'],
    'República Dominicana|Pedernales': ['Pedernales'],
    'República Dominicana|Peravia': ['Baní'],
    'República Dominicana|Puerto Plata': ['Puerto Plata', 'Sosúa'],
    'República Dominicana|Samaná': ['Samaná', 'Las Terrenas'],
    'República Dominicana|San Cristóbal': [
      'San Cristóbal',
      'Villa Altagracia',
    ],
    'República Dominicana|San José de Ocoa': ['San José de Ocoa'],
    'República Dominicana|San Juan': ['San Juan de la Maguana'],
    'República Dominicana|San Pedro de Macorís': ['San Pedro de Macorís'],
    'República Dominicana|Sánchez Ramírez': ['Cotuí'],
    'República Dominicana|Santiago': [
      'Santiago de los Caballeros',
      'Villa Bisonó',
    ],
    'República Dominicana|Santiago Rodríguez': ['Sabaneta'],
    'República Dominicana|Santo Domingo': [
      'Santo Domingo Este',
      'Santo Domingo Norte',
      'Santo Domingo Oeste',
      'Los Alcarrizos',
      'Boca Chica',
    ],
    'República Dominicana|Valverde': ['Mao'],

    // ── Uruguay ──
    'Uruguay|Artigas': ['Artigas'],
    'Uruguay|Canelones': [
      'Las Piedras',
      'Ciudad de la Costa',
      'Pando',
      'La Paz',
      'Canelones',
      'Barros Blancos',
    ],
    'Uruguay|Cerro Largo': ['Melo'],
    'Uruguay|Colonia': ['Colonia del Sacramento'],
    'Uruguay|Durazno': ['Durazno'],
    'Uruguay|Flores': ['Trinidad'],
    'Uruguay|Florida': ['Florida'],
    'Uruguay|Lavalleja': ['Minas'],
    'Uruguay|Maldonado': ['Maldonado', 'Punta del Este', 'San Carlos'],
    'Uruguay|Montevideo': ['Montevideo'],
    'Uruguay|Paysandú': ['Paysandú'],
    'Uruguay|Río Negro': ['Fray Bentos'],
    'Uruguay|Rivera': ['Rivera'],
    'Uruguay|Rocha': ['Rocha'],
    'Uruguay|Salto': ['Salto'],
    'Uruguay|San José': ['San José de Mayo'],
    'Uruguay|Soriano': ['Mercedes'],
    'Uruguay|Tacuarembó': ['Tacuarembó'],
    'Uruguay|Treinta y Tres': ['Treinta y Tres'],

    // ── Venezuela ──
    'Venezuela|Amazonas': ['Puerto Ayacucho'],
    'Venezuela|Anzoátegui': ['Barcelona', 'Puerto La Cruz', 'El Tigre'],
    'Venezuela|Apure': ['San Fernando de Apure'],
    'Venezuela|Aragua': ['Maracay', 'Turmero', 'La Victoria'],
    'Venezuela|Barinas': ['Barinas'],
    'Venezuela|Bolívar': ['Ciudad Bolívar', 'Ciudad Guayana', 'Upata'],
    'Venezuela|Carabobo': [
      'Valencia',
      'Puerto Cabello',
      'Guacara',
      'Naguanagua'
    ],
    'Venezuela|Cojedes': ['San Carlos'],
    'Venezuela|Delta Amacuro': ['Tucupita'],
    'Venezuela|Distrito Capital': ['Caracas'],
    'Venezuela|Falcón': ['Coro', 'Punto Fijo'],
    'Venezuela|Guárico': [
      'San Juan de los Morros',
      'Calabozo',
      'Valle de la Pascua'
    ],
    'Venezuela|Lara': ['Barquisimeto', 'Cabudare', 'Carora'],
    'Venezuela|Mérida': ['Mérida', 'El Vigía', 'Ejido'],
    'Venezuela|Miranda': [
      'Los Teques',
      'Guarenas',
      'Guatire',
      'Charallave',
      'Ocumare del Tuy',
    ],
    'Venezuela|Monagas': ['Maturín'],
    'Venezuela|Nueva Esparta': ['Porlamar', 'La Asunción'],
    'Venezuela|Portuguesa': ['Acarigua', 'Guanare'],
    'Venezuela|Sucre': ['Cumaná', 'Carúpano'],
    'Venezuela|Táchira': ['San Cristóbal', 'Táriba'],
    'Venezuela|Trujillo': ['Valera', 'Trujillo'],
    'Venezuela|Vargas': ['La Guaira', 'Catia La Mar', 'Maiquetía'],
    'Venezuela|Yaracuy': ['San Felipe'],
    'Venezuela|Zulia': [
      'Maracaibo',
      'Cabimas',
      'Ciudad Ojeda',
      'San Francisco',
      'Machiques',
    ],
  };

  /// Returns states for a given country, or empty list if not found.
  static List<String> statesForCountry(String? country) {
    if (country == null || country.isEmpty) return [];
    return states[country] ?? [];
  }

  /// Returns cities for a given country + state, or empty list if not found.
  static List<String> citiesForState(String? country, String? state) {
    if (country == null || country.isEmpty) return [];
    if (state == null || state.isEmpty) {
      // Return all cities for the country
      final result = <String>{};
      for (final entry in cities.entries) {
        if (entry.key.startsWith('$country|')) {
          result.addAll(entry.value);
        }
      }
      final sorted = result.toList()..sort();
      return sorted;
    }
    return cities['$country|$state'] ?? [];
  }

  /// Returns all cities for a given country (across all states).
  static List<String> allCitiesForCountry(String? country) {
    if (country == null || country.isEmpty) return [];
    final result = <String>{};
    for (final entry in cities.entries) {
      if (entry.key.startsWith('$country|')) {
        result.addAll(entry.value);
      }
    }
    final sorted = result.toList()..sort();
    return sorted;
  }
}
