workflows:
  ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: codemagic
    environment:
      groups:
        - codemagic
      flutter: default
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: pro.futboltalent.app
    scripts:
      - name: Get packages
        script: |
          flutter packages pub get
      - name: Initialize keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Apply provisioning profiles
        script: |
          xcode-project use-profiles --project ios/Runner.xcodeproj
      - name: Build iOS
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
